# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: ethascloy
  admin_email: whalebone.earth@gmail.com
  admin_password: okmijn
  email_provider_username: <%= ENV["whalebone.earth"] %>
  email_provider_password: <%= ENV["okmijn12"] %>
  domain_name: theohyeah.com
  secret_key_base: e15d365c94c9b47431c00f7e05d2fad0913b5ef77f45103d6581f777405397479adce58fce61b7f8fbde7121e0714c5ec1d09435ca0caad951e34add39efc74f


test:
  domain_name: theoyeah.com
  secret_key_base: e15d365c94c9b47431c00f7e05d2fad0913b5ef77f45103d6581f777405397479adce58fce61b7f8fbde7121e0714c5ec1d09435ca0caad951e34add39efc74f


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ethascloy"] %>
  admin_email: <%= ENV["whalebone.earth@gmail.com"] %>
  admin_password: <%= ENV["OKMijnuhb123!"] %>
  email_provider_username: <%= ENV["whalebone.earth"] %>
  email_provider_password: <%= ENV["okmijn12"] %>
  domain_name: <%= ENV["http://floating-brushlands-3375.herokuapp.com/"] %>
  secret_key_base: <%= ENV["e15d365c94c9b47431c00f7e05d2fad0913b5ef77f45103d6581f777405397479adce58fce61b7f8fbde7121e0714c5ec1d09435ca0caad951e34add39efc74f"] %>
